import "./globals.css"
import type { Metadata } from "next"
import { Footer } from "@/components/Footer"
import { Header } from "../components/Header"
import { Montserrat } from "next/font/google"

const montserrat= Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Sky Netics",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`scroll-smooth antialiased bg-gray-50 ${montserrat.variable}`}
      >
        <Header/>
        <main className="max-w-[100rem] mx-auto">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}